#!/bin/bash
if [[ ! -e bower.json ]]; then
  echo 'bower.json file does not exist.  Aborting.'
  exit 1
fi
if [ -z "$1" ]; then
  echo 'A release type must be specified: [major | minor | patch]'
  exit 1
fi
howmany() { echo $#; }
# other is added here to capture a new changelog
MODIFIED_FILES=$(git ls-files --modified --other --exclude-standard)
if [[ $(howmany $MODIFIED_FILES) != "1" ]] || [ "$MODIFIED_FILES" != "CHANGELOG.md" ]; then
  echo "Modified files:" ${MODIFIED_FILES}
  echo "CHANGELOG.md must be the ONLY modified file.  Aborting."
  exit 1
fi
# if changelog is new, it must be added to tracked files
git add CHANGELOG.md
git commit -m 'Update changelog.'
bower version ${1} -m 'Release %s.'
git push
git push --tags
bower version prepatch -m 'Start %s.'
git push
git push --tags
