#!/bin/bash
if [[ ! -e bower.json ]]
  then
    echo 'bower.json file does not exist.  Aborting.'
    exit 1
fi
if [ -z "$1" ]
  then
    echo 'A release type must be specified: [major | minor | patch]'
    exit 1
fi
# incase changelog is new.
git add CHANGELOG.md
git commit -m 'Update changelog.'
bower version ${1} -m 'Release %s.'
git push
git push --tags
bower version prepatch -m 'Start %s.'
git push
git push --tags
