#!/bin/bash
PACKAGE_NAME=$(node -p -e "require('./package.json').name")
PACKAGE_REPO=$(node -p -e "require('./package.json').repository.url")
PACKAGE_DIR=${PWD}
if [ -z "$1" ]
  then
    echo 'A release type must be specified: [major | minor | patch]'
    exit 1
fi
if [[ "$PACKAGE_NAME" == *\/* ]] || [[ "$PACKAGE_NAME" == *\\* ]]
  then
    echo 'Slashes detected in package name.  Aborting.'
    exit 1
fi
# incase changelog is new
git add CHANGELOG.md
git commit -m 'Update changelog.'
npm version $1 -m 'Release %s.'
git push
git push --tags
NEW_VERSION=$(node -p -e "require('./package.json').version")
mkdir /tmp/digital-bazaar-release
if [ $? -ne 0 ]
  then
    echo 'Could not create release folder.  Aborting.'
    exit 1
fi
cd /tmp/digital-bazaar-release
rm -rf ${PACKAGE_NAME}
echo 'Waiting two seconds...'
sleep 2
git clone $PACKAGE_REPO
cd ${PACKAGE_NAME}
git checkout tags/${NEW_VERSION}
npm publish
cd ${PACKAGE_DIR}
npm version prepatch -m 'Start %s.'
git push
git push --tags
