#!/bin/bash
if [[ ! -e package.json ]]; then
  echo 'package.json file does not exist.  Aborting.'
  exit 1
fi
PACKAGE_NAME=$(node -p -e "require('./package.json').name")
PACKAGE_REPO=$(node -p -e "require('./package.json').repository.url")
PACKAGE_DIR=${PWD}
RELEASE_FOLDER="/tmp/digital-bazaar-release"
if [ -z "$1" ]; then
  echo 'A release type must be specified: [major | minor | patch]'
  exit 1
fi
if [[ "$PACKAGE_NAME" == *\/* ]] || [[ "$PACKAGE_NAME" == *\\* ]]; then
  echo 'Slashes detected in package name.  Aborting.'
  exit 1
fi
# prepare release folder
if [ ! -d "${RELEASE_FOLDER}" ]; then
  mkdir -p "${RELEASE_FOLDER}"
  if [ $? -ne 0 ]; then
    echo 'Could not create release folder.  Aborting.'
    exit 1
  fi
fi
howmany() { echo $#; }
MODIFIED_FILES=$(git ls-files --modified)
if [[ $(howmany $MODIFIED_FILES) != "1" ]] || [ "$MODIFIED_FILES" != "CHANGELOG.md" ]; then
  echo "Modified files:" ${MODIFIED_FILES}
  echo "CHANGELOG.md must be the ONLY modified file.  Aborting."
  exit 1
fi
# if changelog is new, it must be added to tracked files
git add CHANGELOG.md
git commit -m 'Update changelog.'
npm version $1 -m 'Release %s.'
git push
git push --tags
NEW_VERSION=$(node -p -e "require('./package.json').version")
cd "${RELEASE_FOLDER}"
rm -rf ${PACKAGE_NAME}
echo 'Waiting two seconds...'
sleep 2
git clone $PACKAGE_REPO
cd ${PACKAGE_NAME}
git checkout tags/v${NEW_VERSION}
npm publish
cd ${PACKAGE_DIR}
npm version prepatch -m 'Start %s.'
git push
git push --tags
